### ISSUE TITLE
test compatibility with MDAnalysis 2.0.0

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/pmda#148]
### Expected behaviour
pmda works with MDAnalysis 2.0.0 (or at least only installs MDA < 2.0 if it's not compatible)

### Actual behaviour
I don't know — needs to be tested.

### TODO
- [ ] test against MDA 2.x (possibly when updating CI #146 ) and report if anything is broken
- [ ] possibly fix things so that it works with 2.x
- [ ] think about deprecating MDA 1.x dependence and make a final release fully compatible with 1.x
- [ ] follow NEP29 as does MDA from 2.1 onwards
